# Generated by Django 3.0.7 on 2020-12-16 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20201124_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(default='Breakfast', max_length=50),
        ),
    ]
